### ISSUE TITLE
Support SwiftTileserverCache 2.0

### ISSUE THREAD

**Issue by 123FLO321** [PartTimeJS/WDR#10]
- `/static` route is deprecated in SwiftTileserverCache version 1 and removed in version 2
- use `/staticmap` instead

Using Templates:
- Check SwiftTileserverCache beta (vapor branch) readme for Templating info

Using Pregenerate:
- Post to `/staticmap?pregenerate=true&regeneratable=true`
- Use URL im embed: `/staticmap/pregenerated/:id`

Using Get (not recommended): 
- Use URL im embed `/staticmap` with info as query parameters

**Comment by PartTimeJS** [comment]
WDR Updated to support SwiftTileserverCache 2.0
