### ISSUE TITLE
Invalid Embed filename (raid_eggs.js)

### ISSUE THREAD

**Issue by rileypool** [PartTimeJS/WDR#25]
FILE: WDR/src/feeds/raid.js
LINE: 59
OLD CODE: `Embed_Config = require(WDR.Dir + '/configs/embeds/raid_eggs.js');`
NEW CODE:  `Embed_Config = require(WDR.Dir + '/configs/embeds/raid_egg.js');`

FILE: WDR/src/subscriptions/raid.js
LINE: 119
OLD CODE: `Embed_Config = require(WDR.Dir + '/configs/embeds/raid_eggs.js');`
NEW CODE:  `Embed_Config = require(WDR.Dir + '/configs/embeds/raid_egg.js');`

**Comment by PartTimeJS** [comment]
This is fixed in latest. Changed back to plural file name.
